### ISSUE TITLE
`SyntaxError: Unexpected token` reported when checking `es2019` with dependency declaring class field

### ISSUE THREAD

**Issue by ceisele-r** [yowainwright/es-check#178]
## Requested Update
The following code in a thirdparty library (@lingui/core) used by our application code causes errors when running `es-check es2019 \"./dist/*.js\" --module` against our bundles:
```typescript
class EventEmitter {
  _events = {}; // This line causes the problem
  ...
}
```

The emitted error is:
```
SyntaxError: Unexpected token (114:32617)
    at Parser.pp$4.raise (C:\app\node_modules\acorn\dist\acorn.js:3460:15)
    at Parser.pp$9.unexpected (C:\app\node_modules\acorn\dist\acorn.js:761:10)
    at Parser.pp$9.expect (C:\app\node_modules\acorn\dist\acorn.js:755:28)
    at Parser.pp$5.parseMethod (C:\app\node_modules\acorn\dist\acorn.js:3222:10)
    at Parser.pp$8.parseClassMethod (C:\app\node_modules\acorn\dist\acorn.js:1516:37)
    at Parser.pp$8.parseClassElement (C:\app\node_modules\acorn\dist\acorn.js:1474:12)
    at Parser.pp$8.parseClass (C:\app\node_modules\acorn\dist\acorn.js:1392:26)
    at Parser.pp$8.parseStatement (C:\app\node_modules\acorn\dist\acorn.js:907:19)
    at Parser.pp$8.parseBlock (C:\app\node_modules\acorn\dist\acorn.js:1237:23)
    at Parser.pp$5.parseFunctionBody (C:\app\node_modules\acorn\dist\acorn.js:3286:24)
```

As far as I know, the affected line in `EventEmitter` is valid JS code, thus the error reported seems to be a false positive, isn't it?

## Why Is This Update Needed?
Because `es-check` causes valid JS code to be reported as errors.

## Are There Examples Of This Requested Update Elsewhere?

No

**Comment by ceisele-r** [comment]
This was my fault, I just realized that "(public) class fields" are part of ES2022 even though they have broad browser/node support since a long time already.

See https://caniuse.com/mdn-javascript_classes_public_class_fields and https://v8.dev/features/class-fields#public-class-fields .

=> Checking with target ES2022 works as well as transpiling the code to ES2019 and checking with ES2019.

Sorry for reporting this.
