### ISSUE TITLE
Unexpected token error when using static class properties

### ISSUE THREAD

**Issue by philipkaiser** [yowainwright/es-check#183]
# Description
When running es-check on a file where static class properties are used, we get an unexpected token error directly after the identifier of a static property.

This is the stack-trace that occurs:
```
error: ES-Check: there were 1 ES version matching errors.
info: 
          ES-Check Error:
          ----
          · erroring file: index.js
          · error: SyntaxError: Unexpected token (2:11)
          · see the printed err.stack below for context
          ----

          SyntaxError: Unexpected token (2:11)
    at pp$4.raise (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:3460:15)
    at pp$9.unexpected (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:761:10)
    at pp$9.expect (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:755:28)
    at pp$5.parseMethod (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:3222:10)
    at pp$8.parseClassMethod (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:1516:37)
    at pp$8.parseClassElement (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:1474:12)
    at pp$8.parseClass (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:1392:26)
    at pp$8.parseStatement (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:907:19)
    at pp$8.parseTopLevel (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:818:23)
    at Parser.parse (/.../node_modules/es-check/node_modules/acorn/dist/acorn.js:590:17)
```

based on the stack-trace I assume that the class property is mistakenly parsed as a class method as there is an invocation of `parseClassMethod()` in the middle of the trace. As the error occurs right after the identifier (at the whitespace character) I think the token expected by the method would be a `(`, hence the unexpected token error. Static class methods are parsed without any issue.

# Repro steps
1. create `index.js` file
2. define a class with a static property inside the file: 
```javascript
class Example {
  static x = "y";
}
```
3. run es-check es10 `/path/to/index.js`

**Comment by philipkaiser** [comment]
As this error is thrown by the acorn parser library I also created an issue there: https://github.com/acornjs/acorn/issues/1231

**Comment by philipkaiser** [comment]
As I just learned static class properties were only introduced with es2022. So this is expected behavior and not a bug
