### ISSUE TITLE
`Cannot read property 'includes' of undefined` after updating to 5.2.1

### ISSUE THREAD

**Issue by macobo** [yowainwright/es-check#58]
## Requested Update

Latest version crashes for https://github.com/PostHog/posthog-js/ repo. 5.2.0 continues working.

Stack trace:
```
⟩ npx es-check es5 dist/{array,module}.js -v                         09:42:16

TypeError: Cannot read property 'includes' of undefined
    at /home/macobo/backups/2/projects/posthog-js/node_modules/es-check/index.js:127:16
    at Array.reduce (<anonymous>)
    at Command._action (/home/macobo/backups/2/projects/posthog-js/node_modules/es-check/index.js:126:49)
    at Command._run (/home/macobo/backups/2/projects/posthog-js/node_modules/caporal/lib/command.js:483:42)
    at Program._run (/home/macobo/backups/2/projects/posthog-js/node_modules/caporal/lib/program.js:183:16)
    at Program.parse (/home/macobo/backups/2/projects/posthog-js/node_modules/caporal/lib/program.js:289:17)
    at Object.<anonymous> (/home/macobo/backups/2/projects/posthog-js/node_modules/es-check/index.js:202:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at /home/macobo/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

Potential problematic commit: https://github.com/yowainwright/es-check/commit/2922e7d2d414853106d0885125ce6446feb17e93#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R127

**Comment by konstantintieber** [comment]
I can confirm that this is also happening to us on version `5.2.1`. I changed our GitHub Action Workflow to `npx es-check@5.2.0 es5 dist/apps/main/*.js` for now.

**Comment by timwright12** [comment]
same

**Comment by imbyungjun** [comment]
Now, it works. Thanks!
